// Centralized UI labels for the application
// This file serves as a placeholder for i18n and centralized text management

export const labels = {
  // Admin Settings
  admin: {
    title: "System Administration",
    subtitle: "Complete system configuration and management",
    lastSaved: "Last saved:",
    maintenanceMode: "Maintenance Mode",
    systemHealth: "System Health Monitor",
    cpuUsage: "CPU Usage",
    memory: "Memory",
    databaseSize: "Database Size",
    activeUsers: "Active Users",
    loading: "Loading settings...",
    systemConfig: "Global System Configuration",
    currency: "Currency",
    timezone: "Timezone",
    dateFormat: "Date Format",
    gpsAccuracy: "GPS Accuracy (meters)",
    photoQuality: "Photo Quality",
    sessionTimeout: "Session Timeout (minutes)",
    saveSystemSettings: "Save System Settings",
    enableMaintenanceMode: "Enable Maintenance Mode",
    disableMaintenanceMode: "Disable Maintenance Mode",
    dataOperations: "Data Operations",
    refreshData: "Refresh Data",
    reloadFromDatabase: "Reload from database",
    optimizeDatabase: "Optimize Database",
    improvePerformance: "Improve performance",
    clearCache: "Clear Cache",
    resetCachedData: "Reset cached data",
    dataCleanup: "Data Cleanup",
    removeOldRecords: "Remove old records",
    databaseStats: "Database Statistics",
    employees: "Employees",
    attendanceRecords: "Attendance Records",
    leaveRequests: "Leave Requests",
    locations: "Locations",
    authAccessControl: "Authentication & Access Control",
    maxLoginAttempts: "Max Login Attempts",
    lockoutDuration: "Lockout Duration (minutes)",
    passwordExpiry: "Password Expiry (days)",
    enableTwoFactor: "Enable Two-Factor Authentication",
    enforcePasswordComplexity: "Enforce Password Complexity",
    enableAuditLogging: "Enable Audit Logging",
    emailOnLogin: "Email on Login",
    saveSecuritySettings: "Save Security Settings",
    testEmail: "Test Email",
    testWebhook: "Test Webhook",
    testInApp: "Test In-App",
    notificationTestSent: "notification test sent successfully",
    failedToSend: "Failed to send",
    exportAuditLogs: "Export Audit Logs",
    bulkActivate: "Activated users successfully",
    bulkDeactivate: "Deactivated users successfully",
    bulkResetPassword: "Password reset emails sent",
    bulkDelete: "users deleted successfully",
    confirmDeleteUsers: "Are you sure you want to delete",
    usersCannotUndone: "users? This action cannot be undone.",
    underDevelopment: "This section is under development and will be available in a future update.",
    tabs: {
      system: "System",
      data: "Data Management",
      security: "Security",
      users: "Users",
      locations: "Locations",
      notifications: "Notifications",
      backup: "Backup",
      maintenance: "Maintenance",
      integrations: "Integrations",
      audit: "Audit"
    },
    currencies: {
      MUR: "Mauritian Rupee (Rs)",
      USD: "US Dollar ($)",
      EUR: "Euro (€)",
      GBP: "British Pound (£)"
    },
    timezones: {
      mauritius: "Mauritius (UTC+4)",
      utc: "UTC",
      eastern: "Eastern Time",
      london: "London",
      india: "India"
    },
    dateFormats: {
      ddmmyyyy: "DD/MM/YYYY",
      mmddyyyy: "MM/DD/YYYY",
      yyyymmdd: "YYYY-MM-DD"
    },
    photoQualities: {
      low: "Low (Small file size)",
      medium: "Medium (Balanced)",
      high: "High (Best quality)"
    }
  },

  // Company Settings
  company: {
    title: "Company Settings",
    employeeManagement: "Employee Management System Customization",
    unsavedChanges: "Unsaved Changes",
    customized: "Customized",
    exportData: "Export Data",
    cancel: "Cancel",
    save: "Save",
    companyInformation: "Company Information",
    companyName: "Company Name",
    industry: "Industry",
    employees: "Employees",
    primaryColor: "Primary Color",
    shiftSchedule: "Shift Schedule",
    workingHoursPerDay: "Working Hours Per Day",
    workingDaysPerMonth: "Working Days Per Month",
    lunchBreak: "Lunch Break (Minutes)",
    salaryStructure: "Salary Structure",
    defaultMonthlySalary: "Default Monthly Salary",
    overtimeRules: "Overtime Rules",
    allowances: "Allowances",
    mealAllowance: "Meal Allowance",
    enableMealAllowance: "Enable Meal Allowance",
    amount: "Amount",
    minimumHoursRequired: "Minimum Hours Required",
    transportAllowance: "Transport Allowance",
    enableTransportAllowance: "Enable Transport Allowance",
    monthlyCap: "Monthly Cap",
    industryTemplates: "Industry Templates",
    applyPreConfigured: "Apply pre-configured settings for your industry",
    featureConfiguration: "Feature Configuration",
    enableDisableFeatures: "Enable or disable features based on your business needs",
    mauritiusCompliance: "Mauritius Compliance",
    enableMauritiusTax: "Enable Mauritius Tax Compliance",
    statutoryContributions: "Statutory Contributions",
    employeeContributions: "Employee Contributions",
    employerContributions: "Employer Contributions",
    npf: "NPF",
    nsf: "NSF",
    uiCustomization: "User Interface Customization",
    customizeLook: "Customize the look, feel, and terminology of your HR system to match your company culture",
    editUiCustomization: "Edit UI Customization",
    employeeInterface: "Employee Interface Customization. Change",
    dashboard: "dashboard",
    saveButtons: "save buttons",
    employeeName: "employee name",
    colors: "colors",
    terminology: "and terminology.",
    uiCustomizationsActive: "UI Customizations Active",
    customizedIndustry: "Your interface has been customized with industry-specific terminology and branding.",
    quickTemplates: "Quick Templates",
    constructionTemplate: "Construction Template",
    hospitalityTemplate: "Hospitality Template",
    manufacturingTemplate: "Manufacturing Template",
    customizationOptions: "Customization Options",
    navMenuLabels: "Navigation menu labels",
    buttonText: "Button text and terminology",
    formFieldLabels: "Form field labels",
    statusWorkflow: "Status and workflow names",
    colorsBranding: "Colors and branding",
    typographyLayout: "Typography and layout",
    industries: {
      construction: "Construction",
      delivery: "Delivery & Logistics",
      manufacturing: "Manufacturing",
      retail: "Retail",
      services: "Professional Services",
      other: "Other"
    }
  },

  // UI Customization Panel
  uiCustomization: {
    title: "UI Customization",
    labelsText: "Labels & Text",
    brandingTheme: "Branding & Theme",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    resetToDefault: "Reset to Default",
    navigationLabels: "Navigation Labels",
    buttonLabels: "Button Labels",
    formLabels: "Form Labels",
    companyBranding: "Company Branding",
    companyName: "Company Name",
    tagline: "Tagline",
    colorTheme: "Color Theme",
    confirmReset: "Confirm Reset",
    sureReset: "Are you sure you want to reset all customizations to default? This action cannot be undone.",
    reset: "Reset"
  },

  // Common/Shared
  common: {
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Info",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    remove: "Remove",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    export: "Export",
    import: "Import",
    download: "Download",
    upload: "Upload",
    refresh: "Refresh",
    reset: "Reset",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    ok: "OK",
    apply: "Apply",
    clear: "Clear",
    select: "Select",
    selected: "Selected",
    all: "All",
    none: "None",
    enabled: "Enabled",
    disabled: "Disabled",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    failed: "Failed",
    successMessage: "Operation completed successfully",
    errorMessage: "An error occurred",
    warningMessage: "Please check your input",
    infoMessage: "Information"
  }
};

// Export individual sections for easier importing
export const adminLabels = labels.admin;
export const companyLabels = labels.company;
export const uiCustomizationLabels = labels.uiCustomization;
export const commonLabels = labels.common;
